# Generated by Django 4.2.11 on 2026-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Evento', 'Evento'), ('Pastoral', 'Pastoral'), ('Comunidade', 'Comunidade'), ('Aviso', 'Aviso'), ('Liturgia', 'Liturgia')], default='Evento', max_length=50)),
                ('data', models.DateField()),
                ('texto', models.TextField(blank=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
